export class MovimentacaoEntity {
  public idEstoque: string
  public idEmpresa: string
  public idFornecedor: string
  public idInfortecnica: string
  public idReceita: string
  public numerocontrole: number
  public data?: string
  public datavencimento: string
  public datanfe: string
  public embalagemindea: string
  public enviado: string
  public nomeagrotoxico: string
  public idAgrotoxico: number
  public nomeembalagem: string
  public tipoembalagem: number
  public unidademmbalagem: string
  public idEmbalagem: number
  public nomeresponsaveltecnico: string
  public tipomovimentacao: string
  public json: string
  public notafiscal: string
  public numlote: string
  public observacao: string
  public quantidade: number
  public receita: string
  public registroagrotoxico: string
  public serie: string
  public statussc: string
  public createdAt: string
  public updatedAt: string

  constructor (props: any) {
     this.idEstoque = props.id_estoque
     this.idEmpresa = props.id_empresa
     this.idFornecedor = props.id_fornecedor
     this.idInfortecnica = props.id_infortecnica
     this.idReceita = props.id_receita
     this.numerocontrole = props.numerocontrole
     this.data = props.data
     this.datavencimento = props.datavencimento
     this.datanfe = props.datanfe
     this.embalagemindea = props.embalagemindea
     this.enviado = props.enviado
     this.nomeagrotoxico = props.nomeagrotoxico
     this.idAgrotoxico = props.id_agrotoxico
     this.nomeembalagem = props.nomeembalagem
     this.tipoembalagem = props.tipoembalagem
     this.unidademmbalagem = props.unidademmbalagem
     this.idEmbalagem = props.idEmbalagem
     this.nomeresponsaveltecnico = props.nomeresponsaveltecnico
     this.tipomovimentacao = props.tipomovimentacao
     this.json = props.json
     this.notafiscal = props.notafiscal
     this.numlote = props.numlote
     this.observacao = props.observacao
     this.quantidade = props.quantidade
     this.receita = props.receita
     this.registroagrotoxico = props.registroagrotoxico
     this.serie = props.serie
     this.statussc = props.statussc
     this.createdAt = props.createdAt
     this.updatedAt = props.updatedAt
  }
}