export class ReceitaEntity {
  public idReceita: string
  public idEmpresa: string
  public idCliente: string
  public idPropriedade: string
  public idResponsavel: string
  public numeroreceita: string
  public numeroart: string
  public data: string
  public nome: string
  public statusreceita: string
  public observacao: string
  public obsmip: string
  public notafiscal: string
  public serie: string
  public valor: string
  public datafinal: string
  public statussc: string
  public jsonsc: string
  public codretsc: string
  public enviado: string
  public devolucao: string
  public cogoias: string
  public seriesc: string
  public complementoreceita: string
  public chavenfe: string
  public datanfe: string
  public protocolors: string
  public protocolocancelamentors: string
  public contrato: string
  public nomecliente: string
  public nomeresponsavel: string
  public createdAt: string
  public updatedAt: string

  constructor (props: any) {
    this.idReceita = props.id_receita
    this.idEmpresa = props.id_empresa
    this.idCliente = props.id_cliente
    this.idPropriedade = props.id_propriedade
    this.idResponsavel = props.id_responsavel
    this.numeroreceita = props.numeroreceita
    this.numeroart = props.numeroart
    this.data = props.data
    this.nome = props.nome
    this.statusreceita = props.statusreceita
    this.observacao = props.observacao
    this.obsmip = props.obsmip
    this.notafiscal = props.notafiscal
    this.serie = props.serie
    this.valor = props.valor
    this.datafinal = props.datafinal
    this.statussc = props.statussc
    this.jsonsc = props.jsonsc
    this.codretsc = props.codretsc
    this.enviado = props.enviado
    this.devolucao = props.devolucao
    this.cogoias = props.cogoias
    this.seriesc = props.seriesc
    this.complementoreceita = props.complementoreceita
    this.chavenfe = props.chavenfe
    this.datanfe = props.datanfe
    this.protocolors = props.protocolors
    this.protocolocancelamentors = props.protocolocancelamentors
    this.contrato = props.contrato
    this.nomecliente = props.nomecliente
    this.nomeresponsavel = props.nomeresponsavel
    this.createdAt = props.created_at
    this.updatedAt = props.updated_at
  }
}